{{- if not .Values.spec.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.specConfigMap" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  spec.yaml: |
{{ .Values.spec.inline | indent 4 }}
{{- end }}
