{{- if .Values.controlPlane.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-secrets
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  VS_CONTROL_PLANE_KEY: {{ .Values.controlPlane.apiKey | quote }}
  {{- if eq .Values.source.type "neo4j" }}
  VS_NEO4J_PASSWORD: {{ .Values.neo4j.password | quote }}
  {{- if and .Values.neo4j.trustCert.enabled .Values.neo4j.trustCert.pem }}
  neo4j-ca.crt: |
{{ .Values.neo4j.trustCert.pem | indent 4 }}
  {{- end }}
  {{- else if or (eq .Values.source.type "mysql") (eq .Values.source.type "mariadb") }}
  VS_MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  {{- else if or (eq .Values.source.type "kafka") (eq .Values.source.type "redpanda") }}
  VS_KAFKA_SASL_PASSWORD: {{ .Values.kafka.saslPassword | quote }}
  {{- else }}
  VS_PG_PASSWORD: {{ .Values.pg.password | quote }}
  {{- end }}
{{- end }}
