[package]
name = "ventstream-fleet-protocol"
version.workspace = true
edition = "2024"
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build = "0.14"
protoc-bin-vendored = "3"

[lints]
workspace = true
