[package]
name = "ventstream-fleet-client"
version.workspace = true
edition = "2024"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chrono.workspace = true
ventstream-fleet-protocol.workspace = true
prost-types.workspace = true
rand.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true
x509-parser.workspace = true
zeroize.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
